### ISSUE TITLE
Animation changes CSS

### ISSUE THREAD

**Issue by caiz** [lvivski/anima#32]
Hello,

First of all, thanks for this amazing tool! I just touch it, there are some questions to ask.

I have read the doc, but does not seem to set CSS. For example, I want to make an element from white to red. If this is the solution?

Thank you!

**Comment by lvivski** [comment]
Caiz, unfortunately `Anima.js` wasn't designed as a general animation library. It is oriented on GPU-accelerated properties only, so that you can quickly sketch and create your animations and add custom transitions (colors etc) manually later. `Anima.js` can only animate properties you sent in `transform`: `translate`, `rotate`, `scale` and, additionally, the `opacity` property.

**Comment by caiz** [comment]
Thanks a lot! Great work!
